data:
  dataset_folder: data
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv
  use_id: False # nếu set là True thì có sử dụng thông tin id, ngược lại thì không

tokenizer:
  padding: max_length
  max_length: 128
  truncation: True

text_embedding:
  type: pretrained #có 3 loại, pretrained, tf_idf, count_vec
  add_new_token: True
  text_encoder: VietAI/vit5-base
  freeze: False
  d_features: 768
  d_model: 256
  dropout: 0.2

attention:
  layers: 3
  heads: 8
  d_model: 256
  d_key: 64
  d_value: 64
  d_ff: 2048
  d_feature: 2048
  dropout: 0.2
  use_aoa: False

multi_encoder:
  type: co # có 3 loại, co (co-attention), cross (cross-attention), guide (guide-attention)
  d_model: 256
  layers: 3

uni_encoder:
  d_model: 256
  layers: 3

model:
  type_model: t5
  intermediate_dims: 256
  dropout: 0.2

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 100
  patience: 5
  learning_rate: 2.0e-5
  weight_decay: 0.0
  warmup_ratio: 0.0
  warmup_steps: 0
  metric_for_best_model: f1
  per_device_train_batch_size: 16
  per_device_valid_batch_size: 16

inference:
  test_dataset: /content/data/test.csv
  batch_size: 2048